# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy # More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy ASP.Net Core app to Azure Web App - Juno-Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore JobHelperApi/JobHelperApi.csproj

      - name: Build with dotnet
        run: dotnet build JobHelperApi/JobHelperApi.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish JobHelperApi/JobHelperApi.csproj --configuration Release --no-build --output ./publish

      - name: Upload published app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_760ED8D0A9F34603805EE0B125DB8F37 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CC56E0D1C3984C1BA5117C340FBC47B7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BECE76877471495C9EB72B779D6207DF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Juno-Backend'
          slot-name: 'Production'
          package: ./publish
